 [[servers]]
 host =
 port = 636
 use_ssl = true
 start_tls = false
 ssl_skip_verify = false
    
 bind_dn =
 bind_password = ""
 search_filter = "(uid=%s)"
 search_base_dns =

 [servers.attributes]
 name = "givenName"
 surname = "sn"
 username = "uid"
 email = "mail"

 [[servers.group_mappings]]
 group_dn = "*"
 org_role = "Editor"