apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    admin-password: AgA/SDNEo5BFfx5Etd+vzlFaPzVR6hWpk8ezOAM6o/btt/Xn3cKoFfNQW1SpXr1EeyJ1E3hVlNTMC3eDHg/WcFeNIgT+RDHvZepOAW0z+ZtDRkUKSzV2jBuIs0ZweHWezrpkXyBcsxC0ZWBrAiOBf/JSye1Wy0yayEnpjhRz2XzeUq9gevwntw8oezLOkeqJefh5Bd18lqCYFxf2EZr6mgV8+/bdUUb/7ilECBTum7TwZZ9bqrmMAJa+Tii6f+9CDEeuWJD6h0uiyC8Z2+iBotDJIMm/w9QpDnGZi34qZY0skPlnXjhP+WcBI9AivBHvFeQqmqnp/8wrJa9CSHQYOhqnGC/ioEB6kfa4voncQgW/RHupAuhj3G8MaQ0JTn2uHrfXg/t5Au/d6FO5cCMttn6vDJxX19HwmgEqkVLL7T3n0tkHZmWTKGaX4ebsNU8yDMOI0t4SBfskFvwG+WpgoCTv9VpMHAnE35NF9Zq9+qKrUj/E+6EfKkxu2kwy/o+yGwDAA3PyL4ZwGj2F7XpRGcXevEC3yo733Kna6iQ7c3x0EQGWhAwSsNf7syJMTfo0iG/7bezp+pTQb0x2YTccR1eFWS+k9a62bH4jCfulFex877C2kD/aImeS7TJ+t0fexWvyKEwPNfB+6eAlp5DdrDNp1tL2sIOzEDg+NqiR9xn/lfXgIq/WvyJ+UXPwiRer3hoOleRYuIGBCAO3cl01vYUA6H3bRIJLb1R+53Q=
    admin-user: AgCcnFiITx/G1FG5bMqPDePsXB1yXvhWmflVcELP4++U1Z5vCtsrUFvaBFgX7F6Jt4l+Mf02uNbAKkXsuze5iplaflcpekksECTfnpXKsNLJHevmXEhyxPOtsA3I/bHtwoO+z7uY2Y/nztRHosUQrflqZ0xL/F+TMpcDkXekSRuO3zrbHixEirG7qsoA5EHPipXd3qyXE5+ti8ad4aOz3RV2SDh1U46iUkY/rVAK4ECNaiRr/9opX2Y2Vpc1iX3XwvqTwnFBT6RIbUfZH0xxrygBOTqgAi2vTdXFUXZxpqXvwZWsiq9fc+nRCdAMS2H8zUkfMn4745iMHmm+oDwc1vcObii8opB1MC2GInkWe00Pdbf3Xrz9lnScEE+34iuwwsg97pG7KDO39wqjmYJRqjcjx3KUkGoJhvXTK8t587yzm3WVHogRBPjUdgB2FzIYeQfqgu25p2eMk3fZhNoisBz4m8Rzn/jxulLUc+3Xo+6MN2W+TUsr+OM9Ej1fFI23kGNkL7Kd/jYQ77fphYybTPy+dG6FXQvDbGCQVpt3O5Au4+bQ9OBawLce2N5vqXHoV0yvu9rl1PaZvoIy1eCyTHEM/JIYrxM7ZAHmedn1Xk1AKzCUUwtC+HyAPgCTGaH0t0mhRY0yC5Ws6hR7I1H1pKL8BK3eqQBgKqfcnEycYVysvRU++Apv8rBi8LEjwPkIitKeCSc7JQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque

