apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ingress-nginx
  releaseName: ingress
  version: 4.0.6
  repo: https://kubernetes.github.io/ingress-nginx

namespace: default